### ISSUE TITLE
DV.FormでformItemsを宣言して欲しい

### ISSUE THREAD

**Issue by so-yamamoto** [kawasima/dry-validator#2]
【問題の概要】
dry-validator.jsのDV.Formの中にformItemsが記述されていないためgetFormItemsで取得しようとするとエラーとなってしまいます。

--現在記述されているソース--

<pre>
Form = DV.Form = function() {

};
</pre>

【修正してほしい内容】
PJで使用する独自のjsでDVFormからgetFormItemsをしたいのでDV.Formの中にformItemsの宣言をして欲しいです。

--------修正してほしいソース内容-------

<pre>
Form = DV.Form = function() {
     this.formItems = {};
};
</pre>

以上です。よろしくお願いします。

**Comment by so-yamamoto** [comment]
使用している箇所は"kfn-enquete\web\src\main\webapp\js\common.js"の中の"getFormItems()"を使っている箇所です。

------------------現在のソース-------------------

<pre>
    if(executor){
        var values = new DV.Form();
        values._putValue(this,val,false);
        【var errors = executor.execute(values.getFormItems());】
        var error = errors[name];
        if(error && error.length){
            text.errInput(error);
            }
        }
</pre>

-----------------ver0.2.0に対応させたソース----------------------

<pre>
    if(executor){
        var values = new DV.Form();
        values._putValue(this,val,false);
        【var errors = executor.execute(values.formItems());】
        var error = errors[name];
        if(error && error.length){
            text.errInput(error);
            }
        }
</pre>

**Comment by kawasima** [comment]
declined.
